### ISSUE TITLE
Can't validate request params?

### ISSUE THREAD

**Issue by maunier** [nswbmw/koa-scheme#6]
I have a GET request like /apis/users/:userId/base?gender=0. I want to validate the params : userId 、gender and so on. How can i do this?

**Comment by nswbmw** [comment]
try

```
{
  "/apis/users/:userId/base": {
    "params": {
      "userId": "[1-9]+"
    }
  }
}
```

**Comment by maunier** [comment]
No, It can’t work.



祝工作顺利～！

赵瑞

**Comment by nswbmw** [comment]
try [paloma](https://github.com/palomajs/paloma)
