### ISSUE TITLE
validate break change

### ISSUE THREAD

**Issue by yuu2lee4** [nswbmw/koa-scheme#7]
现在validate的入参必须是string

**Comment by nswbmw** [comment]
推荐用 paloma，自带参数验证

**Comment by yuu2lee4** [comment]
项目已经做完了 /(ㄒoㄒ)/~~

**Comment by yuu2lee4** [comment]
建议你把validate依赖写死。。或者兼容一下新版本

**Comment by nswbmw** [comment]
嗯，不过这个项目不打算维护了，有更好用的就维护更好的。。

**Comment by yuu2lee4** [comment]
你这个在koa里面算好用的。。。![](https://i.loli.net/2018/02/27/5a9555a751580.jpg)。。。
